spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: mysql
    url: jdbc:mysql://localhost:3306/MuzixDb
    username: root
    password: Root@123
  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

